---
resources:
  - name: fauna-csharp-repository
    type: git
    icon: github
    source:
      uri: https://github.com/fauna/faunadb-csharp
      branch: oss-705-concourse-ci-automation

jobs:
  - name: release
    serial: true
    public: false
    plan:
      - get: fauna-csharp-repository

      - task: integration-tests
        file: fauna-csharp-repository/concourse/tasks/integration-tests.yml
        privileged: true
        params:
          FAUNA_ROOT_KEY: ((fauna.secret))
          FAUNA_DOMAIN: ((fauna.domain))
          FAUNA_SCHEME: ((fauna.scheme))
          FAUNA_PORT: ((fauna.port))
          FAUNA_REPO_HOST: ((fauna/repo.host))
          FAUNA_REPO_USER: ((fauna/repo.user))
          FAUNA_REPO_PASSWORD: ((fauna/repo.password))

