---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: karlkfi/concourse-dcind

params:
  FAUNA_ROOT_KEY:
  FAUNA_DOMAIN:
  FAUNA_SCHEME:
  FAUNA_PORT:
  FAUNA_REPO_HOST:
  FAUNA_REPO_USER:
  FAUNA_REPO_PASSWORD:

inputs:
  - name: fauna-csharp-repository

run:
  path: entrypoint.sh
  args:
    - bash
    - -ceu
    - |
      docker login $FAUNA_REPO_HOST --username $FAUNA_REPO_USER --password $FAUNA_REPO_PASSWORD > /dev/null 2>&1
      # start containers
      docker-compose -f fauna-csharp-repository/concourse/tasks/integration.yml run tests
      # stop and remove containers
      docker-compose -f fauna-csharp-repository/concourse/tasks/integration.yml down
      # remove volumes
      docker volume rm $(docker volume ls -q)
      docker logout

